### ISSUE TITLE
Wrong usage of `/* @__PURE__ */` annotation

### ISSUE THREAD

**Issue by martines3000** [paulmillr/scure-base#31]
Hi.

I am not sure if this a bug, but I still want to mention it in case it is.

Rollup throws this warning:
![image](https://github.com/paulmillr/scure-base/assets/35891136/7be46b5f-fdd6-4f57-9455-45b51659b349)

For this part of the code:
https://github.com/paulmillr/scure-base/blob/713480919ce9643cdf1a89ddbfb8e0f40dea87e4/index.ts#L412

It probably should be `/* @__NO_SIDE_EFFECTS__ */ ` instead, right ?

Thank you.

**Comment by paulmillr** [comment]
yes

**Comment by rasgo-cc** [comment]
@paulmillr  any chance we could get this into 1.1.7 soon? :)

**Comment by paulmillr** [comment]
it would be great if we'd get https://github.com/paulmillr/scure-base/pull/34 into 1.1.7 in, but we'll need tests for that. Any chance you could add them? @rasgo-cc
