### ISSUE TITLE
Source map errors are emitted during debug

### ISSUE THREAD

**Issue by shamilovtim** [paulmillr/scure-base#32]
Received in v1.1.6

While debugging our project this package throws source map errors in dev tools:
```
Could not read source map for node_modules/%40scure/base/lib/index.js: ENOENT: no such file or directory, open /node_modules/@scure/base/lib/index.js.map'
```

TypeScript, by default, does not generate source maps. If you want TypeScript to produce source maps along with the compiled JavaScript files, you need to set the sourceMap option to true in your tsconfig.

**Comment by paulmillr** [comment]
The tsconfig has proper settings.

package.json `files` does not contain source maps in it.
