### ISSUE TITLE
Feature request: add option to make base32 padding optional

### ISSUE THREAD

**Issue by benjreinhart** [paulmillr/scure-base#33]
Some third-party and/or [standard libraries](https://hexdocs.pm/elixir/1.12/Base.html#encode32/2) support optional padding when encoding and decoding. 

User facing ids that look like the below are an eyesore.

```
> base32.encode(crypto.getRandomValues(new Uint8Array(16)))
'7CI63KSR5ANU3BKSLYUFTGYQPM======'
```

I'm wondering if you would be open to adding a `{padding: false}` option or doing something like https://github.com/paulmillr/scure-base/issues/4 for base32 as well?

**Comment by paulmillr** [comment]
you can add it as base32nopad if you need it
