### ISSUE TITLE
bech32m.encode does not actually accept Uint8Array

### ISSUE THREAD

**Issue by BerkliumBirb** [paulmillr/scure-base#37]
Types suggest that I can pass Uint8Array as an argument, but in runtime it fails with `bech32.encode words should be array of numbers, not object` error.

**Comment by paulmillr** [comment]
Fixed, but please make sure that you really want to pass Uint8Array here, this function accepts array of words (5bit numbers create via .toWords), not bytes.

Use 'encodeFromBytes' if you really want bytes. Encode accepts words as bytes for compatibility with legacy stuff.
