### ISSUE TITLE
Publish to deno.land/x

### ISSUE THREAD

**Issue by jacogr** [paulmillr/scure-base#8]
I would be great if this could be published to deno.land/x. For my specific usages of `@scure/base` in the libs I do publish, we currently point to [esm.sh/@scure/base@1.1.1](https://deno.land/x/polkadot@0.0.2/util-crypto/base58/bs58.ts#L4) so it certainly would help my little corner of the world.

Normally I would make a PR to add `mod.ts` with a simple `export * from './index.ts'` however since there are webhook setup in the repo as well, it is best left as an issue since the single file PR doesn't add that much value to the overall process.

**Comment by paulmillr** [comment]
Still, a PR would be appreciated. This way you could test the fork on your machine first.

**Comment by jacogr** [comment]
Will do.
